/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Toast: typeof import('primevue/toast')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
